# Nome del workflow, che apparirà su GitHub
name: Java CI with Maven

# Trigger: quando eseguire questo workflow
on:
  # Esegui per ogni push sul branch 'master' o 'main'
  push:
    branches: [ "master", "main" ]
  # Esegui anche per le Pull Request verso 'master' o 'main'
  pull_request:
    branches: [ "master", "main" ]

# Lavori da eseguire
jobs:
  build:
    # Il tipo di macchina virtuale su cui eseguire il lavoro
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice del tuo repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Imposta l'ambiente Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # 3. Esegui il build con Maven
      # Il comando 'clean install' compila il codice e esegue i test
      - name: Build with Maven
        run: mvn -B clean install